### PR TITLE
DRAFT Update basement for GHC 9.2

### PR DESCRIPTION
**Pull request by TomMD**
From head hackage commit: 1b155606132ae49c039f807249f15fa0b6a039ca
This is probably not in the form the maintainer would like, but is a
starting point.

### CODE REVIEW

**Comment by sjakobi** [comment]
Ping @vincenthz.

**Comment by andreasabel** [comment]
Ping @vincenthz.

**Comment by TomMD** [comment]
This package (along with memory) is the main hold up for many projects getting going on GHC 9.2.1.  Could a maintainer chime in with guidance? If work is done in parallel that's great and we can close this. If this patch isn't acceptable (and I expect it isn't) then it would just be nice to know what the desired end state looks like.

**Comment by mrkkrp** [comment]
It looks like @vincenthz de facto decided to stop maintaining some of his projects without taking time to communicate his decision to those who depend on his work. He seems to be overall still active on GitHub and most likely aware of these messages. I do not know why, and certainly I don't expect anyone maintain any open source projects if they don't feel like it. But perhaps it would be possible to choose co-maintainers for `foundation` and `memory`, so that we do not end up in a situation where 30+ packages cannot upgrade? That seems easy enough and hopefully won't require much time/energy.

**Comment by ysangkok** [comment]
@mrkkrp Have you seen that [Vincent has said GHC 9.2 work has started](https://groups.google.com/a/haskell.foundation/g/board/c/68K8jlYChFQ/m/sWj_s96HBQAJ)?

**Comment by mrkkrp** [comment]
@ysangkok No I haven't. I do not follow any Google groups. Re @vincenthz's response: fair enough, but why not post a link stating his position for people who just follow GitHub threads like this one? Why does he expect everyone to find answers in the depth of a Google groups discussion? It is really not hard to comment on a pull request like this one. Silence only serves fostering confusion among people who are interested in this work moving along.

I maintain a few libraries too, and I always answer explicitly to everyone even if I have already answered a similar question elsewhere.

**Comment by vincenthz** [comment]
@mrkkrp I don't expect people to find answers in the depth of a google group, please don't invent some random positions from my silence.

anyway this PR went nowhere since it was a `HeadHackageUtils` module just added in the tree, and has now been done in n integrated way.

**Pull request closed without merging**
