### PR TITLE
Add Conduit.sourceList

### PR DESCRIPTION
**Pull request by ndmitchell**
As @vincenthz suggested I use in #331 but didn't really exist.

### CODE REVIEW

**Comment by NicolasDP** [comment]
Vincent does that often.

**Comment by NicolasDP** [comment]
This could be generalised to `sourceCollection` constrained to `Mappable`.

**Comment by ndmitchell** [comment]
I'd ideally use `mapM_` to do that, but it turns out `mapM_` in foundation is all kinds of wrong (see #334). Perhaps include this as is, and generalising to Mappable in future?

At the same time, you probably want to stick with sinkList (it's not generalisable in the same easy ways), so maybe for symmetry it should always be sourceList?

**Comment by ndmitchell** [comment]
I added `yields` which is generalised to any `Foldable`.

**Pull request merged**
