### PR TITLE
[#120] Add elem not elem

### PR DESCRIPTION
**Pull request by JanGe**
- [x] Add to all collections
- [x] Tests
- [x] Benchmark `String.elem` vs. `Text.any (== elem)`
- [ ] Improve performance

I not sure, I can dig deeper into this in the next few days. So if someone wants to push this over the finish line, feel free to take this as a starting point.

### CODE REVIEW

**Comment by vincenthz** [comment]
nice, good addition. it's a really good approach: start with the list implementation, add benchmarks, then smash the numbers :-)

**Comment by vincenthz** [comment]
damn you @JanGe, I got nerd snapped ! :)

```
benchmarking types/String/Elem/ascii/String
time                 26.26 ns   (25.87 ns .. 26.60 ns)
                     0.998 R²   (0.997 R² .. 0.999 R²)
mean                 26.07 ns   (25.60 ns .. 26.56 ns)
std dev              1.535 ns   (1.301 ns .. 1.999 ns)
variance introduced by outliers: 79% (severely inflated)
             
benchmarking types/String/Elem/ascii/Text
time                 112.2 ns   (110.2 ns .. 114.7 ns)
                     0.997 R²   (0.996 R² .. 0.998 R²)
mean                 113.4 ns   (111.1 ns .. 115.8 ns)
std dev              7.747 ns   (6.056 ns .. 10.82 ns)
variance introduced by outliers: 82% (severely inflated)
             
benchmarking types/String/Elem/mascii/String
time                 22.91 ns   (22.33 ns .. 23.49 ns)
                     0.996 R²   (0.995 R² .. 0.998 R²)
mean                 22.79 ns   (22.38 ns .. 23.18 ns)
std dev              1.361 ns   (1.209 ns .. 1.583 ns)
variance introduced by outliers: 80% (severely inflated)
             
benchmarking types/String/Elem/mascii/Text
time                 69.92 ns   (68.89 ns .. 71.08 ns)
                     0.998 R²   (0.997 R² .. 0.998 R²)
mean                 71.00 ns   (69.89 ns .. 72.53 ns)
std dev              4.373 ns   (3.573 ns .. 6.492 ns)
variance introduced by outliers: 79% (severely inflated)
             
benchmarking types/String/Elem/uni1/String
time                 622.0 ns   (609.0 ns .. 635.5 ns)
                     0.997 R²   (0.994 R² .. 0.998 R²)
mean                 626.7 ns   (615.4 ns .. 637.1 ns)
std dev              38.24 ns   (31.45 ns .. 46.48 ns)
variance introduced by outliers: 75% (severely inflated)
             
benchmarking types/String/Elem/uni1/Text
time                 1.559 μs   (1.541 μs .. 1.580 μs)
                     0.998 R²   (0.998 R² .. 0.999 R²)
mean                 1.570 μs   (1.547 μs .. 1.602 μs)
std dev              86.76 ns   (70.02 ns .. 122.9 ns)
variance introduced by outliers: 70% (severely inflated)
             
benchmarking types/String/Elem/uni2/String
time                 451.5 ns   (445.4 ns .. 458.0 ns)
                     0.998 R²   (0.997 R² .. 0.999 R²)
mean                 459.0 ns   (451.8 ns .. 468.4 ns)
std dev              27.11 ns   (21.04 ns .. 38.83 ns)
variance introduced by outliers: 75% (severely inflated)
             
benchmarking types/String/Elem/uni2/Text
time                 1.319 μs   (1.305 μs .. 1.334 μs)
                     0.999 R²   (0.998 R² .. 0.999 R²)
mean                 1.321 μs   (1.305 μs .. 1.340 μs)
std dev              55.48 ns   (44.38 ns .. 74.68 ns)
variance introduced by outliers: 57% (severely inflated)
```

**Comment by vincenthz** [comment]
pushed at add-elem-notElem on the main repo

**Comment by JanGe** [comment]
That's some impressive numbers! I added your commit to this branch.

**Comment by vincenthz** [comment]
should we just merge this, and deal with the remaining optimisation later ?

**Comment by JanGe** [comment]
Yes, I think that's safe to do. We should probably  add benchmarks for arrays against `vector` first either way.

**Pull request merged**
