### PR TITLE
Does not compile with GHC 7.4

### PR DESCRIPTION
**Pull request by alanz**

### CODE REVIEW

**Comment by vincenthz** [comment]
it's not because of base that it doesn't compile, it's because of using unboxed tuples in pattern match that is not supported by the *compiler*.

**Comment by alanz** [comment]
Yes, but I am using base as a proxy for the compiler, to rule out the older one that no longer works.

**Comment by vincenthz** [comment]
That sounds semantically wrong (hypothetically: what if I have my own ghc 7.4 with support for unboxed tuple in pattern position but with the same base)

`Tested-with` is the compilers we support in foundation

**Comment by ndmitchell** [comment]
Semantically wrong, yes. But still quite convenient... The package vs compiler distinction is broken, but the patch would still be valuable.

**Pull request closed without merging**
