### PR TITLE
CI for GHC 8.0 - 9.0 using cabal generated by Haskell CI

### PR DESCRIPTION
**Pull request by andreasabel**
CI for GHC 8.0 - 9.0 using cabal generated by [Haskell CI](https://github.com/haskell-CI/haskell-ci).

Successful run at: https://github.com/andreasabel/foundation/actions/runs/1478297872.

Will run on repo as soon as merged into `master`.

### CODE REVIEW

**Comment by andreasabel** [comment]
ping @vincenthz

**Comment by andreasabel** [comment]
ping @vincenthz

**Comment by andreasabel** [comment]
ping @vincenthz

**Comment by vincenthz** [comment]
I don't use cabal or this `haskell-ci` (aka `multi-ghc-travis`) but https://github.com/vincenthz/haskell-ci

**Comment by andreasabel** [comment]
> I don't use cabal or this `haskell-ci` (aka `multi-ghc-travis`) but [vincenthz/haskell-ci](https://github.com/vincenthz/haskell-ci)

Ah, didn't know about your CI generator.  Looks interesting, as it can generate CI using `stack` (I have been looking for a tool like this).  Can it target GitHub Actions?

**Comment by vincenthz** [comment]
I need to refresh it, as it bitroted a bit (or more exactly the CI situation evolved), and very likely remove the travis / appveyor target for github actions only

**Comment by andreasabel** [comment]
Great, please alert me once it works for GHA!

**Pull request closed without merging**
