### PR TITLE
Support for GHC 9 in `basement`

### LINKED ISSUE #536: unsafeCoerce# will be gone in GHC 8.12
Just a heads up: I realised through a broken build with a recent GHC HEAD that `basement` uses `unsafeCoerce#` (rather than `unsafeCoerce`). That primop will be gone as of 8.12, see https://gitlab.haskell.org/ghc/ghc/-/merge_requests/1869 and the issues it fixes.

Sorry for the breakage, but primops AFAIK aren't really part of any versioning policy.

### LINKED ISSUE #548: Cannot build basement with GHC 9.0: unsafeCoerce# no longer exported by GHC.Prim in base 4.15+
Hello,

I wanted to bring to your attention that I could not build my [package pandoc-plot](https://github.com/LaurentRDC/pandoc-plot) with GHC 9.0.1 because in basement-0.0.11, `unsafeCoerce#` is imported from `GHC.Prim`:

```haskell
...
basement                         > [16 of 84] Compiling Basement.Floating
basement                         > [17 of 84] Compiling Basement.Monad
basement                         > 
basement                         > /tmp/stack-68bc6b9780c2c4d5/basement-0.0.11/Basement/Monad.hs:98:31: error:
basement                         >     Variable not in scope:
basement                         >       unsafeCoerce#
...
```

From the [migrating guide](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.0#unsafecoerce):

> The unsafeCoerce# function has been moved from GHC.Prim to Unsafe.Coerce. As a result, attempting to import unsafeCoerce# from GHC.Prim (or GHC.Base, which previously re-exported unsafeCoerce#) will result in an error with GHC 9.0. A backwards-compatible way to fix the error is to import unsafeCoerce# from GHC.Exts instead.

### PR DESCRIPTION
**Pull request by LaurentRDC**
This PR fixes #536 and fixes #548.

I could not test with ghc-9.0.1 on my machine, but at least the tests pass for GHC 8.

### CODE REVIEW

**Comment by LaurentRDC** [comment]
I don't understand where is the problem involving `Prelude.chr`

**Comment by Bodigrim** [comment]
I've seen `Prelude.chr` error in other packages built against GHC 9.0. Seems it has something to do with `stack` itself, because `cabal` builds are unaffected in my experience.

**Comment by Bodigrim** [comment]
See https://github.com/commercialhaskell/stack/issues/5486

**Comment by LaurentRDC** [comment]
Allright, thank you. I guess this PR is blocked until then, unless someone else can test locally with GHC 9

**Comment by harendra-kumar** [comment]
@LaurentRDC I have tested it with GHC 9.0, built `gauge` with it successfully. I think we can go ahead an commit it if someone has reviewed it.

**Comment by LaurentRDC** [comment]
Great, I removed the CI test for GHC 9. It's ready to go!

**Comment by LaurentRDC** [comment]
@haskell-foundation Can someone take a look at this? Thanks!

**Comment by danwdart** [comment]
This certainly seems to compile well for me.

**Comment by WillSewell** [comment]
Great to see GHC 9 support added to `basement` in this PR. However support still needs to be added to `foundation`: https://github.com/haskell-foundation/foundation/issues/551. That might not be clear from this PR title/description.

**Comment by patrickt** [comment]
Would love to see this merged, as the fact that `basement` doesn’t build means `gauge` and thereby `fused-effects` can’t move to GHC 9 yet'

**Comment by EmilGedda** [comment]
> Great to see GHC 9 support added to `basement` in this PR. However support still needs to be added to `foundation`: #551. That might not be clear from this PR title/description.

There is already a fix for #551 (which would be the PR #540), which is just waiting for approval and merge.

**Comment by Bodigrim** [comment]
FWIW if blocked because of `gauge`, you can switch to [`tasty-bench`](http://hackage.haskell.org/package/tasty-bench). It is a drop-in replacement, which is even lighter and compatible with GHC 9.0.

**Comment by patrickt** [comment]
Why was the above comment minimized/blocked? Seems like a perfectly reasonable observation, given that this PR hasn’t landed yet.

**Comment by LaurentRDC** [comment]
This PR has been superseeded by commit 3c195907c7e7c41fa0888237b6e36cdbde67df59 so I'm closing it.

**Pull request closed without merging**
