### PR TITLE
added text and examples to bifunctor documentation

### PR DESCRIPTION
**Pull request by GinBaby**
I just thought it'd be nice to have more explanation and examples of bifunctor in the documentation; I PRd `base` with the same changes, so they will stay the same. I'm not sure if that was a priority or not.

### CODE REVIEW

**Comment by vincenthz** [comment]
Thanks, much better documentation already ! beware the trailing spaces next time please.

**Comment by GinBaby** [comment]
Thank you! I'll be more careful about the trailing spaces next time. Cheers
:)

**Comment by ndmitchell** [comment]
@GinBaby - don’t be careful, just reconfigure your text editor :)

**Comment by GinBaby** [comment]
Hahahaha, yes, I will!! :)

**Pull request merged**
