### PR TITLE
String prof optimisations

### PR DESCRIPTION
**Pull request by vincenthz**
mainly optimizing validation (benefiting `UArray Word8 -> String`) and `toList :: String -> [char]`, but probably also improving other benchs.

after:
```
types/String/FromUTF8/ascii/String       mean 238.6 ns  ( +- 4.627 ns  )
types/String/FromUTF8/mascii/String      mean 967.1 ns  ( +- 11.53 ns  )
types/String/FromUTF8/uni1/String        mean 1.199 μs  ( +- 98.72 ns  )
types/String/FromUTF8/uni2/String        mean 829.9 ns  ( +- 24.39 ns  )
types/String/Unpack/ascii/String         mean 3.937 μs  ( +- 104.9 ns  )
types/String/Unpack/mascii/String        mean 8.178 μs  ( +- 150.0 ns  )
types/String/Unpack/uni1/String          mean 3.000 μs  ( +- 123.1 ns  )
types/String/Unpack/uni2/String          mean 2.231 μs  ( +- 107.6 ns  )
```

before:

```
types/String/FromUTF8/ascii/String       mean 330.0 ns  ( +- 16.28 ns  )
types/String/FromUTF8/mascii/String      mean 1.134 μs  ( +- 25.78 ns  )
types/String/FromUTF8/uni1/String        mean 1.527 μs  ( +- 13.97 ns  )
types/String/FromUTF8/uni2/String        mean 1.105 μs  ( +- 33.75 ns  )
types/String/Unpack/ascii/String         mean 10.17 μs  ( +- 92.49 ns  )
types/String/Unpack/mascii/String        mean 19.46 μs  ( +- 136.7 ns  )
types/String/Unpack/uni1/String          mean 6.792 μs  ( +- 44.58 ns  )
types/String/Unpack/uni2/String          mean 5.127 μs  ( +- 205.1 ns  )
```

### CODE REVIEW

**Comment by vincenthz** [comment]
@ndmitchell should be of interest, should lower runtime/allocations in weeder

**Comment by vincenthz** [comment]
@ndmitchell do we have a volunteer for merging back the code just like for the Mutable algorithms ? :)

**Comment by ndmitchell** [comment]
@vincenthz not me :)

**Comment by ciderale** [comment]
@vincenthz By "merging back like for the Mutable algorithm", do you mean something along the line of #414 that I did with the sortByInplace? I could have look at further unifying more of the algorithms.

**Comment by vincenthz** [comment]
@ciderale yes, I think it would be interesting to see if we can do the same for the immutable bits.

I had a quick try when doing the reverse, but that turn out a bit painful to re-organise so I did the copy-pasta thing.

**Comment by ciderale** [comment]
I started working on the Algorithms in PrimArray. I'm about to prepare the PR for that. If that looks okay, I can continue on Strings.

**Comment by ndmitchell** [comment]
I benchmarked, but it's hard to spot a meaningful change in time (and like a fool, I deleted the old one before I ran memory). Useful to have anyway!

**Pull request merged**
