### PR TITLE
Import unsafeCoerce# from GHC.Exts for compatibility with GHC 8.12

### LINKED ISSUE #536: unsafeCoerce# will be gone in GHC 8.12
Just a heads up: I realised through a broken build with a recent GHC HEAD that `basement` uses `unsafeCoerce#` (rather than `unsafeCoerce`). That primop will be gone as of 8.12, see https://gitlab.haskell.org/ghc/ghc/-/merge_requests/1869 and the issues it fixes.

Sorry for the breakage, but primops AFAIK aren't really part of any versioning policy.

### PR DESCRIPTION
**Pull request by sgraf812**
Fixes #536.

### CODE REVIEW

**Comment by osa1** [comment]
Could we merge this please?

**Comment by vilem-ff** [comment]
I'm running into this issue as well.

**Comment by galenhuntington** [comment]
Is this repo abandoned?  I came here to pull request this myself, only to find it had already been done 5 months ago and still hasn't been merged.  In fact, probably #535 should be merged.

**Comment by vaibhavsagar** [comment]
I saw https://github.com/haskell-infra/hackage-trustees/issues/284#issuecomment-750738981, can this be merged now that GHC 9.0 is generally available @vincenthz?

**Comment by vincenthz** [comment]
prereleased of stack 10 hours ago that work with ghc-9, basement-0.12 and foundation-0.26 released

**Pull request closed without merging**
