### PR TITLE
Patch basement-0.0.6/Basement/Terminal/Size.hsc

### PR DESCRIPTION
**Pull request by asyropoulos**
I tried to compile basement-0.0.6 on OpenIndiana with ghc-8.2.2 and it failed. I discoved that the following patch solves the problem:

diff -Naur basement-0.0.6/Basement/Terminal/Size.hsc basement-0.0.6.new/Basement/Terminal/Size.hsc
--- basement-0.0.6/Basement/Terminal/Size.hsc 2017-11-11 19:03:59.000000000 +0000
+++ basement-0.0.6.new/Basement/Terminal/Size.hsc 2018-01-21 15:03:03.899338329 +0000
@@ -20,6 +20,9 @@
#include <windows.h>
#elif defined FOUNDATION_SYSTEM_UNIX
#include <sys/ioctl.h>
+#ifdef __sun
+#include <sys/termios.h>
+#endif
#endif

#include <stdio.h>

Could include this patch in the source distribution?

### CODE REVIEW

**Comment by NicolasDP** [comment]
Hi @asyropoulos , nice try. But no it is not like this. I see from your github profile you are not used to working on open source project.

The usual workflow in open source projects on github is the following:

1. fork the project you want to send changes;
2. clone your fork into your local workspace;
3. commit changes locally;
4. push your changes to your fork;
5. create a pull request to the upstream repository with your changes.

I hope this won't be your last contribution to an open source project, you can find lot of tutorials to explain how git and github works out there if it helps.

Would you be happy if _for now_ if I commit your patch but with you authoring it ?

**Comment by ndmitchell** [comment]
Thanks for the patch @asyropoulos - the knowledge is useful - but if you follow the standard GitHub flow then the code could be merged directly (you get the credit more explicitly, and the maintainers have a lot less work to do). See https://guides.github.com/activities/forking/ and https://guides.github.com/introduction/flow/ for the rough overview.

**Comment by asyropoulos** [comment]
I have double checked it and the patch makes it possible to compile basement-0.0.6 under Solaris. Please apply/push/commit/whatever_the_verb the patch to the source code if this is possible. And yes I have contributed to many projects. Some contributions were like this one and others created new functionality to tools, etc. However, in all cases I was just reporting the problem and the solution and that was all. I admit it that I have no experience with github and git in general.

**Comment by NicolasDP** [comment]
thanks, I have applied the patch with #472

**Pull request closed without merging**
